[package]
name = "freenet-email-inbox"
version = "0.0.1"
edition = "2021"
rust-version = "1.58.0"
resolver = "2"
publish = false

[dependencies]
bincode = { workspace = true }
ed25519-dalek = { workspace = true }
chrono = { workspace = true }
locutus-stdlib = { workspace = true }
locutus-aft-interface = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib"]
